<a href="https://colab.research.google.com/github/RazyAnas/MachineLearning/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Creating numpy arrays

In [5]:
import numpy as np

In [6]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [7]:
type(arr1)

numpy.ndarray

In [8]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [9]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
arr4 = np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
arr6 = np.arange(10)

In [13]:
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr6= np.arange(5,15,2)

In [15]:
arr6

array([ 5,  7,  9, 11, 13])

In [16]:
arr7 = np.linspace(10, 20, 10) #start, stop, total values in bw

In [17]:
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [18]:
arr8 = arr7.copy()

In [19]:
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

## Numpy Array Properties and attributes

In [20]:
# shape, nDim, Size, ItemSize, Dtype, astype() -> numpy is a class so properties and attributes will be there

In [21]:
arr1

array([1, 2, 3, 4, 5])

In [22]:
arr1.shape

(5,)

In [23]:
arr2.shape

(2, 3)

In [24]:
arr9 = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]]])

In [25]:
arr9.shape

(2, 3, 3)

In [26]:
arr9

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [27]:
arr9.ndim

3

In [28]:
arr2.ndim

2

In [29]:
arr1.ndim

1

In [30]:
arr1.size

5

In [31]:
arr1

array([1, 2, 3, 4, 5])

In [32]:
arr9.size

18

In [33]:
arr9.itemsize

8

In [34]:
arr8.itemsize

8

In [35]:
arr9.dtype

dtype('int64')

In [36]:
arr8.dtype

dtype('float64')

In [37]:
# convert type of data
arr9.astype('float')

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]],

       [[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]]])

In [38]:
arr8.astype('int')

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 20])

In [39]:
# cleaning data -> reduce size of data in ML

## Numpy Array Vs Python Lists

In [40]:
# Arrays VS List
# Faster
# Convenient
# Less memory

In [41]:
# Less memory

In [42]:
lista = range(100)

In [43]:
lista


range(0, 100)

In [44]:
arr11 = np.arange(100)

In [45]:
arr11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [46]:
import sys

In [47]:
print(sys.getsizeof(87)*len(lista))

2800


In [48]:
print(arr11.itemsize*arr11.size)

800


In [49]:
# how fast

In [50]:
import time

In [51]:
x = range(10000000)
y = range(10000000, 20000000)

start_time = time.time() # current time stored in start time

c = [(x,y) for x,y in zip(x,y)]
print(time.time()-start_time)

2.1796226501464844


In [53]:
y=np.arange(100000000)
z=np.arange(100000000, 200000000)

start_time = time.time() # stores current time
c= z+y
print(time.time()-start_time)

0.8329446315765381


## Indexing slicing and iteration

In [54]:
arr12 = np.arange(24)

In [64]:
arr12 = arr12.reshape(6,4)

In [65]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [58]:
arr1

array([1, 2, 3, 4, 5])

In [59]:
arr1[3
     ]

np.int64(4)

In [61]:
arr1[2:4]

array([3, 4])

In [62]:
arr1[-1]

np.int64(5)

In [66]:
arr12[2]

array([ 8,  9, 10, 11])

In [70]:
arr12[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [71]:
arr12[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [75]:
arr12[:,2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [77]:
arr12[2:4, 1:3]

array([[ 9, 10],
       [13, 14]])

In [80]:
arr12[4:7, 2:4]

array([[18, 19],
       [22, 23]])

In [81]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [83]:
for i in arr12:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [86]:
for i in np.nditer(arr12): # n dimensional iterator
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
