<a href="https://colab.research.google.com/github/RazyAnas/MachineLearning/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Creating numpy arrays

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [3]:
type(arr1)

numpy.ndarray

In [30]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [7]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
arr4 = np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
arr6 = np.arange(10)

In [15]:
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr6= np.arange(5,15,2)

In [17]:
arr6

array([ 5,  7,  9, 11, 13])

In [18]:
arr7 = np.linspace(10, 20, 10) #start, stop, total values in bw

In [20]:
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [21]:
arr8 = arr7.copy()

In [22]:
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

## Numpy Array Properties and attributes

In [24]:
# shape, nDim, Size, ItemSize, Dtype, astype() -> numpy is a class so properties and attributes will be there

In [25]:
arr1

array([1, 2, 3, 4, 5])

In [26]:
arr1.shape

(5,)

In [31]:
arr2.shape

(2, 3)

In [32]:
arr9 = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]]])

In [33]:
arr9.shape

(2, 3, 3)

In [34]:
arr9

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [35]:
arr9.ndim

3

In [36]:
arr2.ndim

2

In [37]:
arr1.ndim

1